### ISSUE TITLE
Minizip link is dead 

### ISSUE THREAD

**Issue by Pastitas** [tpimh/flatcam-flatpak#2]
The actual archive is 
http://zlib.net/**fossils**/zlib-1.2.11.tar.gz

Without that fossils bit the link dies when new releases come out

**Comment by tpimh** [comment]
I think this one is coming from [org.qgis.qgis](https://github.com/flathub/org.qgis.qgis), I should check how this is solved there. But simply replacing the link seems like a good solution to me.

**Comment by tpimh** [comment]
Zlib is now updated, please test if it works now and feel free to reopen the issue if it doesn't.
